services:
  postgres:
    image: postgres:latest
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data

volumes:
  bank_postgres_data:
