server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
    default-schema: public

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  config: classpath:logback-spring.xml

jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B4274OMH4TY1F6E5C3A596D635A75327855
  access-token-validity: 36000000 # 10 hour